name: restaurant_app
description: "A restaurant app for submission dicoding academy."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  image_picker: ^1.1.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/
